# Site settings
title: "Cloud Security Web App Challenge: Secure-Pass-Sentinel"
description: "Enhance and deploy a password strength checker using serverless cloud technologies"
baseurl: "/Cloud-Security-Web-App-Challenge"
url: "https://jqcvsc.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false

# Google Analytics
# google_analytics: [Your Google Analytics tracking ID]

# Custom CSS (this will be applied on top of Cayman theme)
style: |
  body {
    font-family: 'Roboto', sans-serif;
    line-height: 1.6;
  }
  .page-header {
    padding: 30px 10px;
  }
  .project-name {
    font-size: 36px;
    font-weight: 700;
  }
  .project-tagline {
    font-size: 18px;
    font-weight: 300;
  }
  .main-content {
    padding-top: 40px;
  }
  h1, h2, h3, h4, h5, h6 {
    color: #1e88e5;
    font-weight: 600;
  }
  a {
    color: #039be5;
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }
  code {
    background-color: #f1f8e9;
    border: 1px solid #c5e1a5;
    border-radius: 3px;
    padding: 2px 5px;
  }
  pre code {
    display: block;
    padding: 10px;
    overflow-x: auto;
  }
  .highlight {
    background-color: #f1f8e9;
    border: 1px solid #c5e1a5;
    border-radius: 3px;
    padding: 10px;
  }

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
