remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Cloud Security Web App Challenge: Secure-Pass-Sentinel"
description: "Enhance and deploy a password strength checker using serverless cloud technologies"

# Custom CSS
style: |
  body {
    font-family: 'Roboto', sans-serif;
    line-height: 1.6;
  }
  #header_wrap .inner {
    padding: 30px 10px 30px 10px;
  }
  #project_title {
    font-size: 36px;
    font-weight: 700;
    text-shadow: 1px 1px 3px rgba(0,0,0,0.3);
  }
  #project_tagline {
    font-size: 18px;
    font-weight: 300;
  }
  #main_content {
    padding-top: 40px;
  }
  h1, h2, h3, h4, h5, h6 {
    color: #1e88e5;
    font-weight: 600;
  }
  a {
    color: #039be5;
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }
  code {
    background-color: #f1f8e9;
    border: 1px solid #c5e1a5;
    border-radius: 3px;
    padding: 2px 5px;
  }
  pre code {
    display: block;
    padding: 10px;
    overflow-x: auto;
  }
  .highlight {
    background-color: #f1f8e9;
    border: 1px solid #c5e1a5;
    border-radius: 3px;
    padding: 10px;
  }

# Google Analytics
google_analytics: [Your Google Analytics tracking ID]

# GitHub repository
github:
  is_project_page: true
  repository_url: "https://github.com/JQCVSC/Cloud-Security-Web-App-Challenge"
