remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: "Cloud Security Web App Challenge: Secure-Pass-Sentinel"
description: "Enhance and deploy a password strength checker using serverless cloud technologies"
